config/routes.rb
BasicAuth::Application.routes.draw do

  root :to => "home#index"
  get "sign_in" => "authentication#sign_in"
  get "signed_out" => "authentication#signed_out"
  get "change_password" => "authentication#change_password"
  get "forgot_password" => "authentication#forgot_password"
  get "new_user" => "authentication#new_user"
  get "password_sent" => "authentication#password_sent"
  get "how_it_works" => "home#how_it_works"
  post "sign_in" => "authentication#login"
  post "new_user" => "authentication#register"
  put "new_user" => "authentication#register"
end

app/models/user.rb
#Note that the table name is users, hence the models name must be user.rb

class User <ActiveRecord::Base
  attr_accessible :email, :username, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username, :on => :create
  validates_presence_of :email, :on => :create
  validates_uniqueness_of :email
  validates_uniqueness_of :username

  def initialize(attributes = {})
    super # must allow the active record to initialize!
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def self.authenticate_by_email (email, password)
    user = find_by_email(email)
    if user && user.password_hash== BCrypt::Engine::hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def self.authenticate_by_username (username, password)
    user = find_by_username username
    if user && user.password_hash == BCrypt::Engine::hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  def encrypt_password
    if password.present?
      self.password_salt= BCrypt::Engine::generate_salt
      self.password_hash= BCrypt::Engine::hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :curr_user

  def curr_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def sign_in
    @user = User.new
  end

  def login
    u_or_e = params[:user][:username]
    pass = params[:user][:password]

    if u_or_e.rindex('@')
       user = User.authenticate_by_email(u_or_e, pass)
    else
      user = User.authenticate_by_username(u_or_e, pass)
    end

    if verify_recaptcha
      if user
        session[:user_id] = user.id
        flash[:notice] = "Welcome"
        redirect_to :root
      else
        flash[:error] = "Invalid username/email or password"
        redirect_to :sign_in
      end
    else
      flash.delete(:recaptcha_error) # get rid of the recaptcha error being flashed by the gem.
      flash[:error] = 'reCAPTCHA is incorrect. Please try again.'
      redirect_to  :sign_in
    end

  end

  def signed_out
    session[:user_id] = nil
    flash[:notice] = "Successfully Logged out!!! Visit again!!!"
  end

  def new_user
    @user = User.new
  end

  def register
    @user = User.new(params[:user])

    if verify_recaptcha
      if @user.valid?
        @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Welcome #{@user.username}"
        redirect_to :root
      else
        render :action => "new_user"
      end
    else
      flash.delete(:recaptcha_error) # get rid of the recaptcha error being flashed by the gem.
      flash.now[:error] = 'reCAPTCHA is incorrect. Please try again.'
      render :action => "new_user"
    end
  end

end

app/controllers/home_controller.rb
class HomeController <ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_field_error(model, field)
    s=""

    if !model.errors[field].empty?
      s =
          <<-EOHTML
           <div id="error_message">
             #{model.errors[field][0]}
           </div>
      EOHTML
    end

    s.html_safe
  end

end

app/views/authentication/new_user.html.erb
<p>Sign Up</p>
<%= form_for @user, :as => :user, :url => new_user_path, :method => :put do |f| %>
    <p>
      <%= f.label 'Mobile:' %><br/>
      <%= f.text_field :username %>
      <%= show_field_error(@user, :username) %>
    </p>
    <p>
      <%= f.label 'email:' %><br/>
      <%= f.text_field :email %>
      <%= show_field_error(@user, :email) %>
    </p>
    <p>
      <%= f.label 'password:' %><br/>
      <%= f.password_field :password %>
      <%= show_field_error(@user, :password) %>
    </p>
    <p>
      <%= f.label 'password confirmation:' %><br/>
      <%= f.password_field :password_confirmation %>
      <%= show_field_error(@user, :password_confirmation) %>
    </p>
    <p><%= recaptcha_tags %></p>
    <p>
      <%= f.submit 'Sign Up' %>&nbsp;&nbsp;&nbsp;
      <%= f.submit 'Clear Form', :type => 'reset' %>
    </p>
<% end %>

app/views/authentication/sign_in.html.erb
<p>Sign In</p>
<%= form_for @user, :as => :user, :url => sign_in_path(@user) do |f| %>
    <p>
      <%= f.label 'Mobile or Email:' %><br />
      <%= f.text_field :username %>
    </p>
    <p>
      <%= f.label 'password:' %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= recaptcha_tags %>
    </p>
    <p>
      <%= f.submit 'Sign In' %>&nbsp;&nbsp;&nbsp;
      <%= f.submit 'Clear Form', :type => 'reset' %>
    </p>
<% end %>

app/views/home/how_it_works.html.erb
<p> It works as if it works.</p>

app/views/home/index.html.erb
<p> Welcome to CoRVance </p>
<p> Aa to gaye ho jooge kahan </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoRVance</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<p>
  <% if curr_user %>
      Hi <%= curr_user.username %>.
      <%= link_to "Sign Out", signed_out_path %>
  <% else %>
      <%= link_to "Register Now", new_user_path %> or
      <%= link_to "Sign In", sign_in_path %>
      <%= link_to "How it works", how_it_works_path %>
  <% end %>
</p>

<%= yield %>

</body>
</html>